print('Name: ', end = " ")
name = input()
print("Age: ", end = " ")
age = input()
print("Height: ", end = ' ')
Height = input()
print("Weight: ")
weight = input()
print(f"Hi my name is {name}, my age is {age}, Height is {Height}, weight is {weight}.")
print("\nGuru")